import XCTest
@testable import SpringFestivalCrush

/// Level solver. The quick test guards against unwinnable levels on every run; the report
/// is opt-in (`tools/simulate_levels.sh`) because thousands of games take a minute or two.
@MainActor
final class LevelBalanceTests: XCTestCase {
    private var environment: [String: String] { ProcessInfo.processInfo.environment }

    /// Every bundled level, in play order, optionally narrowed by `SIM_LEVELS=Rabbit,Tiger_Level_12`.
    private var levels: [String] {
        let all = Zodiac.all.flatMap { zodiac in
            (0 ..< zodiac.numLevels).map { "\(zodiac.zodiacType.name)_Level_\($0 + 1)" }
        }
        let filters = (environment["SIM_LEVELS"] ?? "").split(separator: ",").map(String.init).filter { !$0.isEmpty }
        guard !filters.isEmpty else { return all }
        return all.filter { name in filters.contains { name == $0 || name.hasPrefix($0 + "_") } }
    }

    /// Plays each level until the first win. Even the hardest shipped level (about 1 win in 10)
    /// wins within 150 games all but never, so a failure means the level cannot be won.
    func testEveryLevelIsWinnableBySensiblePlay() {
        for filename in levels {
            var games = 0
            var stuck = 0
            var won = false
            while !won, games < 150 {
                let outcome = LevelSimulator(filename: filename, policy: .greedy).play()
                games += 1
                won = outcome.won
                if outcome.stuck { stuck += 1 }
            }
            XCTAssertTrue(won, "\(filename) was never won in \(games) sensible games")
            XCTAssertLessThanOrEqual(stuck, games / 10, "\(filename) dead-ends without a shuffle")
        }
    }

    /// Lock goals count locks as they finally open, so a goal can never ask for more than the board holds.
    func testLockGoalsFitTheLocksOnTheBoard() throws {
        for filename in levels {
            let data = try XCTUnwrap(LevelData.loadFrom(file: filename), filename)
            guard let goal = data.levelGoal.levelTarget.lock, data.boss?.kind != .rabbit else { continue }
            let lockTiles: Set<Tile.TileType> = [.lock, .doubleLock, .vaultLock]
            let locks = data.tiles.joined().filter { lockTiles.contains(Tile.TileType(rawValue: $0) ?? .empty) }.count
            XCTAssertLessThanOrEqual(goal, locks, "\(filename) asks for \(goal) locks but has \(locks)")
        }
    }

    func testBalanceReport() throws {
        guard let runs = environment["SIM_RUNS"].flatMap(Int.init), runs > 0 else {
            throw XCTSkip("Set SIM_RUNS (see tools/simulate_levels.sh) to produce the balance report.")
        }
        var lines = [
            "| Level | Diff | Moves | Win (sensible) | ★ | ★★ | ★★★ | Moves left | Win score | Loss progress | Short in losses | Win (random) |",
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|---:|",
        ]
        func percent(_ value: Double) -> String { String(format: "%.0f%%", value * 100) }
        for filename in levels {
            let greedy = LevelBalance(filename: filename, policy: .greedy, runs: runs)
            let random = LevelBalance(filename: filename, policy: .random, runs: max(1, runs / 2))
            lines.append("| \(filename.replacingOccurrences(of: "_Level_", with: " ")) | \(greedy.difficulty) | \(greedy.moves) "
                + "| \(percent(greedy.winRate)) | \(percent(greedy.starRates[0])) | \(percent(greedy.starRates[1])) "
                + "| \(percent(greedy.starRates[2])) | \(greedy.medianMovesLeft) | \(greedy.medianWinScore) "
                + "| \(percent(greedy.lossProgress)) | \(greedy.shortfall) "
                + "| \(percent(random.winRate)) |")
        }
        let report = lines.joined(separator: "\n")
        print("\n" + report + "\n")
        if let path = environment["SIM_REPORT"], !path.isEmpty {
            let header = "# Level balance report\n\n\(runs) sensible and \(max(1, runs / 2)) random games per level, "
                + "generated by `tools/simulate_levels.sh`. See [rabbit-chapter-and-level-solver.md](rabbit-chapter-and-level-solver.md) "
                + "for what each column means.\n\n"
            try (header + report + "\n").write(toFile: path, atomically: true, encoding: .utf8)
        }
    }
}
